"""add external_job_id to jobs

Revision ID: c5f66c977663
Revises: 74bcb5cb4cda
Create Date: 2026-07-30 14:36:18.043211

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5f66c977663'
down_revision: Union[str, None] = '74bcb5cb4cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('api_keys_key_hash_key', 'api_keys', type_='unique')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.alter_column('candidates', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('candidates', 'resume_file_path',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('candidates', 'pipeline_status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending_parse'::character varying"))
    op.drop_index('ix_candidates_email', table_name='candidates')
    op.drop_index('ix_candidates_id', table_name='candidates')
    op.drop_index('ix_candidates_job_id', table_name='candidates')
    op.alter_column('interview_reports', 'strengths',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('interview_reports', 'weaknesses',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('interview_reports', 'final_recommendation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint('interview_reports_interview_session_id_key', 'interview_reports', type_='unique')
    op.drop_index('ix_interview_reports_candidate_id', table_name='interview_reports')
    op.drop_index('ix_interview_reports_id', table_name='interview_reports')
    op.drop_index('ix_interview_reports_interview_session_id', table_name='interview_reports')
    op.drop_index('ix_interview_reports_job_id', table_name='interview_reports')
    op.alter_column('interview_sessions', 'unique_token',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('interview_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint('interview_sessions_livekit_room_name_key', 'interview_sessions', type_='unique')
    op.drop_index('ix_interview_sessions_candidate_id', table_name='interview_sessions')
    op.drop_index('ix_interview_sessions_id', table_name='interview_sessions')
    op.drop_index('ix_interview_sessions_job_id', table_name='interview_sessions')
    op.drop_index('ix_interview_sessions_unique_token', table_name='interview_sessions')
    op.drop_index('uq_interview_sessions_active_per_candidate_job', table_name='interview_sessions', postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'in_progress'::character varying])::text[]))")
    op.add_column('jobs', sa.Column('external_job_id', sa.String(length=255), nullable=True))
    op.alter_column('jobs', 'required_skills',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('jobs', 'experience_max',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'screening_questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('jobs', 'interview_questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_index('ix_jobs_id', table_name='jobs')
    op.drop_column('jobs', 'interview_focus')
    op.alter_column('screening_calls', 'call_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('screening_calls', 'availability',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('screening_calls', 'communication_quality',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('screening_calls', 'result',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index('ix_screening_calls_candidate_id', table_name='screening_calls')
    op.drop_index('ix_screening_calls_id', table_name='screening_calls')
    op.drop_index('ix_screening_calls_job_id', table_name='screening_calls')
    op.drop_constraint('screening_calls_vapi_call_id_key', 'screening_calls', type_='unique')
    op.alter_column('shortlist_results', 'recommendation',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('shortlist_results', 'strengths',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('shortlist_results', 'gaps',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('shortlist_results', 'hr_decision',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('shortlist_results', 'hr_feedback_type',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('ix_shortlist_results_candidate_id', table_name='shortlist_results')
    op.drop_index('ix_shortlist_results_id', table_name='shortlist_results')
    op.drop_index('ix_shortlist_results_job_id', table_name='shortlist_results')
    op.drop_constraint('shortlist_results_candidate_id_key', 'shortlist_results', type_='unique')
    op.drop_constraint('tenant_invites_token_key', 'tenant_invites', type_='unique')
    op.drop_index('uq_tenant_invites_active_email', table_name='tenant_invites', postgresql_where='(accepted_at IS NULL)')
    op.drop_index('ix_tenant_invites_token', table_name='tenant_invites')
    op.create_index(op.f('ix_tenant_invites_token'), 'tenant_invites', ['token'], unique=True)
    op.drop_constraint('tenants_slug_key', 'tenants', type_='unique')
    op.drop_index('ix_tenants_slug', table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=False)
    op.create_unique_constraint('tenants_slug_key', 'tenants', ['slug'])
    op.drop_index(op.f('ix_tenant_invites_token'), table_name='tenant_invites')
    op.create_index('ix_tenant_invites_token', 'tenant_invites', ['token'], unique=False)
    op.create_index('uq_tenant_invites_active_email', 'tenant_invites', ['tenant_id', 'email'], unique=True, postgresql_where='(accepted_at IS NULL)')
    op.create_unique_constraint('tenant_invites_token_key', 'tenant_invites', ['token'])
    op.create_unique_constraint('shortlist_results_candidate_id_key', 'shortlist_results', ['candidate_id'])
    op.create_index('ix_shortlist_results_job_id', 'shortlist_results', ['job_id'], unique=False)
    op.create_index('ix_shortlist_results_id', 'shortlist_results', ['id'], unique=False)
    op.create_index('ix_shortlist_results_candidate_id', 'shortlist_results', ['candidate_id'], unique=False)
    op.alter_column('shortlist_results', 'hr_feedback_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('shortlist_results', 'hr_decision',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('shortlist_results', 'gaps',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('shortlist_results', 'strengths',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('shortlist_results', 'recommendation',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_unique_constraint('screening_calls_vapi_call_id_key', 'screening_calls', ['vapi_call_id'])
    op.create_index('ix_screening_calls_job_id', 'screening_calls', ['job_id'], unique=False)
    op.create_index('ix_screening_calls_id', 'screening_calls', ['id'], unique=False)
    op.create_index('ix_screening_calls_candidate_id', 'screening_calls', ['candidate_id'], unique=False)
    op.alter_column('screening_calls', 'result',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('screening_calls', 'communication_quality',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('screening_calls', 'availability',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('screening_calls', 'call_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.add_column('jobs', sa.Column('interview_focus', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.create_index('ix_jobs_id', 'jobs', ['id'], unique=False)
    op.alter_column('jobs', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('jobs', 'interview_questions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('jobs', 'screening_questions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('jobs', 'experience_max',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'required_skills',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.drop_column('jobs', 'external_job_id')
    op.create_index('uq_interview_sessions_active_per_candidate_job', 'interview_sessions', ['candidate_id', 'job_id'], unique=True, postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'in_progress'::character varying])::text[]))")
    op.create_index('ix_interview_sessions_unique_token', 'interview_sessions', ['unique_token'], unique=False)
    op.create_index('ix_interview_sessions_job_id', 'interview_sessions', ['job_id'], unique=False)
    op.create_index('ix_interview_sessions_id', 'interview_sessions', ['id'], unique=False)
    op.create_index('ix_interview_sessions_candidate_id', 'interview_sessions', ['candidate_id'], unique=False)
    op.create_unique_constraint('interview_sessions_livekit_room_name_key', 'interview_sessions', ['livekit_room_name'])
    op.alter_column('interview_sessions', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('interview_sessions', 'unique_token',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.create_index('ix_interview_reports_job_id', 'interview_reports', ['job_id'], unique=False)
    op.create_index('ix_interview_reports_interview_session_id', 'interview_reports', ['interview_session_id'], unique=False)
    op.create_index('ix_interview_reports_id', 'interview_reports', ['id'], unique=False)
    op.create_index('ix_interview_reports_candidate_id', 'interview_reports', ['candidate_id'], unique=False)
    op.create_unique_constraint('interview_reports_interview_session_id_key', 'interview_reports', ['interview_session_id'])
    op.alter_column('interview_reports', 'final_recommendation',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('interview_reports', 'weaknesses',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('interview_reports', 'strengths',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.create_index('ix_candidates_job_id', 'candidates', ['job_id'], unique=False)
    op.create_index('ix_candidates_id', 'candidates', ['id'], unique=False)
    op.create_index('ix_candidates_email', 'candidates', ['email'], unique=False)
    op.alter_column('candidates', 'pipeline_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'pending_parse'::character varying"))
    op.alter_column('candidates', 'resume_file_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('candidates', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', [sa.text('created_at DESC')], unique=False)
    op.create_unique_constraint('api_keys_key_hash_key', 'api_keys', ['key_hash'])
    # ### end Alembic commands ###
